[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/api/playlist"
  [headers.values]
    Cache-Control = "no-store"